### ISSUE TITLE
custom "Unsaved Changes" modal

### ISSUE THREAD

**Issue by 4kh00** [jerimiah-smiggins/smiggins#189]
The modal when I have unsaved changes in Settings is just the default version. It just looks slightly visually jarring. I would label this as an enhancement, priority low, and I have no clue about the difficulty. This site looks awesome - thanks for making it.

**Comment by trinkey** [comment]
i can see that although modals are kinda difficult to make properly. i will definitely keep this in mind

**Comment by trinkey** [comment]
doing this however will pave the way to add more custom modals throughout the site

**Comment by trinkey** [comment]
the only problem is that i'm pretty sure the only way to prevent someone from leaving the site is using the builtin popup, because if you could do anything then sites could just eat the request and not close. it could be possible if all the external links were replaced with buttons that trigger the unsaved thing before redirecting although that's too much effort for it to be worth it

**Comment by trinkey** [comment]
this has been added to the dev branch to the extent of what i believe to be possible (only triggers when pressing links), this will be fully added in the next version (v0.13.5 or v0.14.0)
